export interface CompanyProp {
  name: string,
  creation: string,
  modified: string,
  modified_by: string,
  owner: string,
  docstatus: number,
  idx: number,
  company_name: string,
  abbr: string,
  default_currency: string,
  country: string,
  is_group: number,
  default_holiday_list: null,
  default_letter_head: null,
  tax_id: null,
  domain: null,
  date_of_establishment: null,
  parent_company: null,
  company_logo: null,
  date_of_incorporation: null,
  phone_no: null,
  email: null,
  company_description: null,
  date_of_commencement: null,
  fax: null,
  website: null,
  create_chart_of_accounts_based_on: string,
  existing_company: null,
  chart_of_accounts: string,
  default_buying_terms: null,
  sales_monthly_history: string,
  monthly_sales_target: number,
  total_monthly_sales: number,
  default_selling_terms: null,
  default_warehouse_for_sales_return: null,
  credit_limit: number,
  transactions_annual_history: string,
  default_bank_account: string,
  default_cash_account: string,
  default_receivable_account: string,
  round_off_account: string,
  round_off_cost_center: string,
  write_off_account: string,
  exchange_gain_loss_account: string,
  unrealized_exchange_gain_loss_account: string | null,
  unrealized_profit_loss_account: string | null,
  allow_account_creation_against_child_company: number | null,
  default_payable_account: string,
  default_expense_account: string,
  default_income_account: string,
  default_deferred_revenue_account: string | null,
  default_deferred_expense_account: string | null,
  default_discount_account: string | null,
  payment_terms: string | null,
  cost_center: string,
  default_finance_book: string | null,
  enable_perpetual_inventory: number,
  enable_provisional_accounting_for_non_stock_items: number | null,
  default_inventory_account: string,
  stock_adjustment_account: string,
  default_in_transit_warehouse: string | null,
  stock_received_but_not_billed: string,
  default_provisional_account: string | null,
  expenses_included_in_valuation: string,
  accumulated_depreciation_account: string,
  depreciation_expense_account: string,
  series_for_depreciation_entry: string | null,
  expenses_included_in_asset_valuation: string | null,
  disposal_account: string,
  depreciation_cost_center: string,
  capital_work_in_progress_account: string | null,
  asset_received_but_not_billed: string | null,
  exception_budget_approver_role: string | null,
  registration_details: string | null,
  lft: number | null,
  rgt: number | null,
  old_parent: string,
  _user_tags: string,
  _comments: string,
  _assign: string,
  _liked_by: string
}